spring:
  application:
    name: cost-efficient-rag

  datasource:
    url: jdbc:postgresql://ep-still-wave-axwhfhlu.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_EqzR0WvdY5cL
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      api-key: AIzaSyD5E4Tdh3pxzZmAEVppmlz0paLtIDb_MXc
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: gemini-1.5-flash
      embedding:
        options:
          model: text-embedding-004
    vectorstore:
      pgvector:
        table-name: vector_store
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE

rag:
  chunking:
    default-chunk-size: 512
    default-chunk-overlap: 64